name: Update README on Merge

on:
  push:
    branches:
      - main
    # Optionally restrict to specific types of pushes, e.g., merges
    # types:
    #   - merged

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the Python version you require

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install markdown
    - name: Run pydoc extraction script
      run: |
        python scripts/pydoc_parser.py README.md

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md with pydoc documentation" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
